adicionando cidadania pera brasileiros
deandreamatias/brazil-tech-expats-wiki pull request #3
Opened 2024-01-23 12:09 UTC by denissilveira

2024-01-23 12:16 UTC, deandreamatias requested changes
Adicionaria algum link ao site onde constam os requisitos para a nacionalidade. Desta maneira, ficaria mais abrangente a seção e não seria somente das provas do Cervantes

2024-01-23 12:16 UTC, deandreamatias commented on countries/spain/README.md
> +Para os brasileiros, a obtenção da cidadania espanhola torna-se viável após residirem legalmente na Espanha por um período de 2 anos. Um dos requisitos essenciais é a comprovação do conhecimento da c
Importante adicionar aqui que é 2 anos APÓS obter o TIE (cartão físico) não o NIE (número)

2024-01-23 12:16 UTC, deandreamatias commented on countries/spain/README.md
> +### Cidadania
Talvez incluiria a palavra Nacionalidade, pois é outro termo muito usado para se referir ao mesmo

2024-01-23 12:39 UTC, denissilveira commented
> Adicionaria algum link ao site onde constam os requisitos para a nacionalidade. Desta maneira, ficaria mais abrangente a seção e não seria somente das provas do Cervantes

Buscando sobre isso, quase todos os links vao ser de empresas vendendo consultoria, advogados, afins, nao achei um link mais oficial para colocar.. mas vou tentar ver se encontro algo.

2024-01-24 13:45 UTC, denissilveira commented
> > > Adicionaria algum link ao site onde constam os requisitos para a nacionalidade. Desta maneira, ficaria mais abrangente a seção e não seria somente das provas do Cervantes
> > 
> > 
> > Buscando sobre isso, quase todos os links vao ser de empresas vendendo consultoria, advogados, afins, nao achei um link mais oficial para colocar.. mas vou tentar ver se encontro algo.
> 
> Eu tinha visto mas não lembrava onde. Achei aqui https://www.mjusticia.gob.es/es/ciudadania/tramite?k=solicitud-nacionalidad-espanola-residencia

Adicionei esse novo link, muito obrigado

2024-01-24 15:58 UTC, deandreamatias approved these changes

2024-01-24 15:58 UTC, merged